// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsI5FIVoK1Pzb237SuEyR9zT0L4aQg7d4',
    appId: '1:335138690315:web:769bcc5594a69710873e0e',
    messagingSenderId: '335138690315',
    projectId: 'spotifyuiclone1120',
    authDomain: 'spotifyuiclone1120.firebaseapp.com',
    storageBucket: 'spotifyuiclone1120.appspot.com',
    measurementId: 'G-SY8GF0T44W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXo_a_WElw-VSYkP8qm73wtILrq-oAv8',
    appId: '1:335138690315:android:f53895c0d7a81621873e0e',
    messagingSenderId: '335138690315',
    projectId: 'spotifyuiclone1120',
    storageBucket: 'spotifyuiclone1120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRTXoGlW4pBwLG2OBYEapZBJ5r5Hr8wA',
    appId: '1:335138690315:ios:9d95e5b4dae293e1873e0e',
    messagingSenderId: '335138690315',
    projectId: 'spotifyuiclone1120',
    storageBucket: 'spotifyuiclone1120.appspot.com',
    iosClientId: '335138690315-md883jmj2kds307tkgb16qv20vj6k7ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyUiClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRTXoGlW4pBwLG2OBYEapZBJ5r5Hr8wA',
    appId: '1:335138690315:ios:9d95e5b4dae293e1873e0e',
    messagingSenderId: '335138690315',
    projectId: 'spotifyuiclone1120',
    storageBucket: 'spotifyuiclone1120.appspot.com',
    iosClientId: '335138690315-md883jmj2kds307tkgb16qv20vj6k7ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyUiClone',
  );
}
